controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_front_article:
    path: /article/{id}
    controller: App\Controller\FrontController::showArticle
    methods: [GET]
    requirements:
        id: \d+

app_front_articles:
    path: /articles
    controller: App\Controller\FrontController::articles
    methods: [GET]

app_front_about:
    path: /about
    controller: App\Controller\FrontController::about
    methods: [GET]

app_front_contact:
    path: /contact
    controller: App\Controller\FrontController::contact
    methods: [GET, POST]

access_denied:
    path: /access-denied
    controller: App\Controller\AccessDeniedController::index

